name: Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: setup docker
        uses: docker/setup-buildx-action@v3
      - name: build
        run: make build
      # - name: push
      #   run: make push
