name: Test
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: setup docker
        uses: docker/setup-buildx-action@v3
      - name: test
        run: make test
